networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgres:16.0
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  account-service:
    build: .
    container_name: rugid-account-service
    ports:
      - 0
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/account
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app
