networks:
  app:

services:
  postgres:
    image: postgres:16.0
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    networks:
      - app

  todo-service:
    build: .
    container_name: todo-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app
