spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: true
  cache:
    type: redis
  redis:
    host: redis-cache
    port: 6379
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: cam.emobile.springtodo
  paths-to-match: /api/v1/**
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
      info:
        enabled: true
